import { expect, openLiveApp, test } from './live';
import { authenticate } from './helpers';

test.describe('full browser voice flow @local-only', () => {
  let sessionToken: string;

  test.beforeAll(async () => {
    sessionToken = await authenticate();
  });

  test('mic click -> real browser capture -> real STT -> transcript in chat', async ({ page }) => {
    await openLiveApp(page, sessionToken);

    // Wait for app to initialize and WS to connect.
    await page.waitForFunction(() => {
      const app = (window as any)._taburaApp;
      if (typeof app?.getState !== 'function') return false;
      const state = app.getState();
      const wsOpen = (window as any).WebSocket.OPEN;
      return Boolean(document.getElementById('indicator'))
        && state?.chatWs?.readyState === wsOpen
        && state?.canvasWs?.readyState === wsOpen;
    }, null, { timeout: 10_000 });
    await page.waitForTimeout(1000);

    // Click the canvas viewport to start recording. The fake audio device
    // streams the Piper WAV generated by the local E2E wrapper.
    await page.locator('#canvas-viewport').click({
      position: { x: 420, y: 320 },
      timeout: 10_000,
    });

    await expect.poll(async () => {
      return page.evaluate(() => {
        const app = (window as any)._taburaApp;
        const state = app?.getState?.();
        return String(state?.voiceLifecycle || '');
      });
    }, { timeout: 8_000 }).toBe('recording');

    // Let the fake device feed the speech segment into the real browser
    // capture path. If VAD has not auto-stopped yet, stop manually so this
    // E2E stays focused on browser capture -> STT -> chat delivery.
    await page.waitForTimeout(3_000);
    const stillRecording = await page.evaluate(() => {
      const app = (window as any)._taburaApp;
      const state = app?.getState?.();
      return String(state?.voiceLifecycle || '') === 'recording';
    });
    if (stillRecording) {
      await page.locator('#canvas-viewport').click({
        position: { x: 420, y: 320 },
        timeout: 10_000,
      });
    }

    // Wait for STT to process the captured audio and for the transcript to
    // appear in the UI.
    await expect.poll(async () => {
      const chatHistory = page.locator('#chat-history');
      const text = await chatHistory.textContent();
      return text && text.trim().length > 0;
    }, {
      message: 'Chat history should contain transcript from voice input',
      timeout: 45_000,
      intervals: [1000],
    }).toBeTruthy();

    // Verify transcript is non-empty and plausible (came from "Hello, this is a test of voice recording")
    const chatText = await page.locator('#chat-history').textContent();
    expect(chatText!.trim().length).toBeGreaterThan(3);
  });
});
